### ISSUE TITLE
Redisdown: how to create new `level-` libs?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/community#116]
Hi!

One of the many great things about the old `level` ecosystem were all of the *down libraries for connecting to different database backends.

Many of these (for example `redisdown`) no longer work on the new `level@8` architecture.

Say that you, a random developer on the internet, want to create `level-redis` for `level@8`- where would you start? How would you go about doing this? Asking for a friend ;)

**Comment by vweevers** [comment]
There's a few ways to go about this:

1. Take an existing `abstract-leveldown` implementation and follow the [upgrade guide of `abstract-level`](https://github.com/Level/abstract-level/blob/main/UPGRADING.md). See also the [FAQ](https://github.com/Level/community#how-do-i-upgrade-to-abstract-level).
2. Start from scratch and read [Private API For Implementors](https://github.com/Level/abstract-level#private-api-for-implementors)
3. Use `memory-level` or other implementations as reference.

Naming-wise, prefer e.g. `redis-level` (i.e. `*-level`).
