### ISSUE TITLE
badges?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/community#12]
Which badges do you want to use for level? (It's fine to say that you don't want any at all :grinning:) Anything in particular that you like more or is a must have? Which badges suck and are useless to you?

I personally like badges a lot, but it's also a fine line between when they are just too many and don't give any "valuable" information.

**Comment by vweevers** [comment]
> I personally like badges a lot, but it's also a fine line between when they are just too many and don't give any "valuable" information.

I'm with you on that.

For starters I think it's a good idea to remove those bulky npm badges

**Comment by vweevers** [comment]
Let's also replace pngs with svgs (the travis badge in [leveldown](https://github.com/level/leveldown) for example).

**Comment by ralphtheninja** [comment]
@vweevers Is it possible to get different looks on travis versus appveyor?

**Comment by vweevers** [comment]
Yeah, we can customize labels and/or colors. For example

[![Travis](https://img.shields.io/travis/Level/leveldown.svg?label=travis)]() [![AppVeyor](https://img.shields.io/appveyor/ci/Level/leveldown.svg?label=appveyor)]()

**Comment by vweevers** [comment]
> I've added the Greenkeeper stuff but now afterwards I'm not sure why we really need that one. Do people care if we use Greenkeeper or not?

@ralphtheninja I think we can remove it in favor of the david-dm badge. The static greenkeeper badge says we (well, you) work hard to ensure dependencies are up-to-date, david-dm shows the actual result of that :)

**Comment by ralphtheninja** [comment]
Makes sense. `david-dm` is more informative.

@vweevers WDYT about adding a link to level-badges that point to the awesome repo?

**Comment by vweevers** [comment]
> WDYT about adding a link to the level badge that point to the awesome repo?

Great idea!
