### ISSUE TITLE
Getting no entry found error in Chrome when using .get("key") 

### ISSUE THREAD

**Issue by kevinkyle4** [Level/community#125]
If I am trying to fetch a value by its key before the value exists in DB it throws a "Entry Not Found" error in browser which crashes app. How do I use .get() to return zero results if entry is not found like in MongoDB?
Thanks

**Comment by vweevers** [comment]
This is by design, but [changing](https://github.com/Level/abstract-level/blob/main/UPGRADING.md) in `abstract-level` 2.0.0. Until then, do:

```js
try {
  await db.get('example')
} catch (err) {
  if (err.code === 'LEVEL_NOT_FOUND') {
    console.log('Not found')
  }
}
```

**Comment by juliangruber** [comment]
Something like this should work:

```js
let value = null
try {
  value = await db.get('key')
} catch (err) {
  if (err.type !== 'NotFoundError') {
    throw err
  }
}
```
