### ISSUE TITLE
GitHub topics?

### ISSUE THREAD

**Issue by vweevers** [Level/community#13]
Does anyone make use of [this](https://help.github.com/articles/about-topics/)? Should we make an effort to have the same set of topics on every repo?

**Comment by ralphtheninja** [comment]
I personally don't use them, although I try to set some.

**Comment by vweevers** [comment]
Added topics to all repos. Some interesting ones:

- https://github.com/topics/abstract-leveldown
- https://github.com/topics/level-packager
- https://github.com/topics/prebuilt-binaries
- https://github.com/search?q=topic%3Anot-maintained+org%3ALevel&type=Repositories
- https://github.com/search?q=topic%3Abrowser+org%3ALevel&type=Repositories
