### ISSUE TITLE
What about sublevels?

### ISSUE THREAD

**Issue by vweevers** [Level/community#14]
I think we need to invest some time in either `level-sublevel` or `subleveldown`, get one of them up to par with latest `levelup`, `abstract-leveldown` and `encoding-down`, maybe deprecate the other.

Thoughts @Level/owners?

**Comment by juliangruber** [comment]
I personally just use bytewise/prefixes now, but would be very happy to have a canonical sublevel implementation

**Comment by ralphtheninja** [comment]
I agree with @juliangruber. But important to note that neither of them are within the level organization. I'd be happy to help out maintaining them though if @dominictarr or @mafintosh agrees to move them. I personally prefer subleveldown.

**Comment by juliangruber** [comment]
> I personally prefer subleveldown.

me too

**Comment by dominictarr** [comment]
I don't use level-sublevel anymore. I've moved on to: http://github.com/flumedb/
If someone wants to take over level-sublevel though, you are welcome to it!
btw, I noticed that bytewise was a performance problem in ssb and I started working on http://github.com/dominictarr/charwise but it's not quite ready yet.

**Comment by finnp** [comment]
There is also [level-spaces](https://github.com/rvagg/level-spaces).

I think it would be nice to have a leveldown-like module that is maintained to work with the latest level.

**Comment by ralphtheninja** [comment]
@finnp Would you accept an invite to Level org? 😄

**Comment by ralphtheninja** [comment]
https://github.com/Level/subleveldown
