### ISSUE TITLE
Move TypeScript to DefinitelyTyped

### ISSUE THREAD

**Issue by vweevers** [Level/community#16]
Because this is about all Level projects, I'm opening it here.

See Level/abstract-leveldown#204 for background or the TLDR: https://github.com/Level/abstract-leveldown/pull/204#issuecomment-367109560.

@Tapppi, @ralphtheninja and I are in favor. Before we discuss the how, let's give @zixia and @MeirionHughes some time to respond.

**Comment by MeirionHughes** [comment]
That's fair enough; we could potentially just rollback the defiantly typed commits that removed the abstract-down and level-down typings; and remove the typings entirely from all level repos. the levelup typings on definitely typed are still there, but incorrect. 

I've been playing with the new inferring mechanism in typescript 2.8, but unfortunately it falls short due to not supporting function overloads. Ultimately, the way levelup is structured makes it very difficult to type and infer from any arbitrary abstract-down.

**Comment by zixia** [comment]
I agree we use DefinitelyTyped to manage _level_ typings because it will give the community the maximum flexibility to maintain the types for our Level projects.

We have too much pain with writing a _.d.ts_ separately with the JavaScript code. I always believe that if we could write all in TypeScript, the world would be better from now, and the JavaScript developer could still write ES6 JavaScript code without any problem.

Anyway, any solution would be a wonderful solution as long as it could make typing work. Let's move on. :)

**Comment by vweevers** [comment]
Alright, that's settled then!

It's your call when to remove the typings from Level packages. Seeing as they were experimental, I think we can do so in minor releases across the board (as if they were pre-1.0.0).

**Comment by MeirionHughes** [comment]
I'll strip out the generics this weekend and reduce the coupling between abstract encoder and levelup. 

We simply need function overload inference in typescript, until then people will just have to make do or make their own interface on-top of levelup. 

`level`, however, can be typed explicitly

**Comment by Tapppi** [comment]
@zixia 

> BTW: We can use the discussion board of Github Org Teams for common TypeScript discussion at here: https://github.com/orgs/Level/teams/typescript

As a warning, that chat is private, not public. I think discussions involving changes to users should be public.

> We simply need function overload inference in typescript, until then people will just have to make do with a general typing or make their own interface on-top of `levelup`.

> `level`, however, can be typed explicitly

I think this sounds like a good plan. I guess `level-rocksdb` etc. also need explicit typings in DT or they won't work?

**Comment by zixia** [comment]
@Tapppi Thanks for the warning, you are right. I thought the discussion is public but it isn't.

**Comment by sqwk** [comment]
Is there a pull request for DefinitelyTyped already? Which typings should get moved/merged?

**Comment by MeirionHughes** [comment]
I wasn't really comfortable doing patch work on Defiantly Typed; potentially for me to further break things for people. :/  I think its better to clear up the typings separately, then if you still want to move them it can be all done in one go. 

I've made a start anyway, see https://github.com/Level/level-typings

I've also made a quick branch in down, encoding, up and abstract to add a `notypes` branch that strips each of their own typings. then `level-typings` directly depends on them (github dep)

**Comment by asross** [comment]
Any plan to address this in the near future? I'm encountering pretty major problems using this library with `@types/levelup` and `@types/leveldown`. It might actually be better to remove those libraries from DefinitelyTyped if they no longer work!

**Comment by asross** [comment]
I was actually able to get things working with https://github.com/Level/typings, thanks @MeirionHughes !

**Comment by MeirionHughes** [comment]
For my work I'll be needing to use leveldb / rockdb, so hopefully I can pencil in some time to move this to DT. Unless someone wants to take over that aspect. 

As far as I can tell the typing s are done, only need to deal with the DT package and sorting out the inter-dependencies. An alternative would be to make each package entirely self-sufficient, at which point they can just be thrown up to DT.

**Comment by zixia** [comment]
Good work @MeirionHughes !

Move TypeScript to DefinitelyTyped +1

And I'm always thinking about to rewrite the JS to TS... because that will make the typing very easy to generate and sync with the latest code.

**Comment by zixia** [comment]
Currently, we had moved all the typings to <https://github.com/Level/typings>, what will we expect the user to use it? I had just upgrade my dep to the latest and found that it seems no good way to integrate with our typings.

If we maintain the typings by ourselves, how about move the Level/typings to DefinitelyTyped, so that we can use @types/encoding-down for convenience?

**Comment by sqwk** [comment]
Is there any guide on how to get this working with the current version of levelup/leveldown?

**Comment by danwbyrne** [comment]
Hello, I'm just getting to this discussion. I'm currently in the process of typing some external libraries we use at https://github.com/neo-one-suite/neo-one/issues/419, and am curious what the status is here for moving to DT.

I see there is already a `Level/typings` and I'm not trying to step on any toes so if you just need someone to do the work of making the DT repo let me know and I am willing. 😃

**Comment by zixia** [comment]
@danwbyrne Thanks for the volunteer! I believe it is very necessary to publish all the `Level/typings` to the DT repo so that we can use `@types/levelXXX` for convenience.

Appreciate for that. @Level/typescript

**Comment by Pajn** [comment]
Is really the situation right now that no level packages can be used with Typescript?

**Comment by vweevers** [comment]
@MeirionHughes Could you explain in more detail what needs to happen in DT, so that @danwbyrne or someone else can pick up the work?

> I was actually able to get things working with https://github.com/Level/typings

@asross Can you share the steps you took? Might help others who're looking for a short-term solution until DT is ready. Thanks all!

**Comment by danwbyrne** [comment]
Seems like it will be pretty straight forward to move the typings over, more of a formatting issue than anything to get them in order for the DT repo. 

The only thing I have noticed is there is already some old typings for `leveldown` and `levelup` on DT now, but their typings don't seem to line up with the ones found at `https://github.com/Level/typings` so I can just submit to overwrite those.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leveldown
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/levelup

**Comment by zixia** [comment]
@danwbyrne Please go ahead, looking forward to seeing the new typings got published!

**Comment by danwbyrne** [comment]
I've submitted a PR for abstract-leveldown, need to wait for that one to go through before I submit for the others as they depend on its typings (also I'm slow and can't submit them all at once :joy:).

**Comment by vweevers** [comment]
> level-codec [..] has its own typings included with it.

That's a leftover, should be moved out of Level/codec.

**Comment by ralphtheninja** [comment]
https://github.com/Level/codec/commit/1cfd23fe8f6686f1ae432587aa7b63e5da1c4a93

**Comment by wookieb** [comment]
I was redirected here from the issue: https://github.com/Level/encoding-down/issues/67#issuecomment-420181986

I'm very sad that you've decided to move typings out of repository. It very error-prone in terms of synchronization of the api. Even now its out of sync since it doesn't say that methods return a promise 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/levelup/index.d.ts
P.s. I'm not going to update it since it's counter productive and effects of my work might be outdated any time.

I understand the reason that many of maintainers don't know typescript but that's the real problem. Developing nowadays almost anything in node without typescript is very error-prone, not reliable, much slower and much harder. 

I'm very sad that that you're throwing away so many valuable traits instead learning typescript basics within an hour.

I was happy to rewrite few libs to typescript as it should be fairly easy, but if you don't want and not willing to change the opinion about typescript then OK.

**Comment by danwbyrne** [comment]
@wookieb I think you are misinformed. From my understanding both of the declaration files for @DefinitelyTyped/levelup and @DefinitetlyTyped/leveldown are incorrect and extremely deprecated.

 The ONLY Level packages that have actually been transferred from Level/Typings as of now (by my efforts) are [abstract-leveldown](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/abstract-leveldown) and [level-codec](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/level-codec) with the rest to follow in the coming weeks.

Hopefully that clears up the situation, I also noticed the levelup/leveldown typings in @DT but as far as I can tell by their contents they are NOT correct nor should you attempt to use them with a recent version of the packages.

**Comment by wookieb** [comment]
@danwbyrne  You're right about DefinitelyTypes but that doesn't matter where the typings are. What matters is that you're creating them manually which has all downsides I've mentioned above.

> Hopefully that clears up the situation, I also noticed the levelup/leveldown typings in DT but as far as I can tell by their contents they are NOT correct nor should you attempt to use them with a recent version of the packages.

How I was suppose to know that? :) 

>  I also can't guarantee that the typings ive moved over are completely correct, so I would really love help or at least another set of eyes on them

Same as with fixing typings in DefinitelyTyped. That doesnt make sense for you to update typing manually as it very quickly outdates.

**Comment by wookieb** [comment]
> You can call that "manual work" but there is no alternative.
The alternative is: Rewrite to typescript. The alternative is javascript with a lot of typings synchronization problems that every popular js library has.

It's not a joke. Please don't get me wrong. I'm not a Typescript fanboy that is coming here to spread "typescript" disease. I'm talking about real solution for real problems. Developing anything in node.js without typings is a real disease. Developing with wrong typings is even more annoying and that happens really really often.

> I hope that you can return the favor and realize that there is a big JavaScript audience.
Not sure what are you trying to say.

**Comment by vweevers** [comment]
I'll rephrase: rewriting to TypeScript is not an option because many people are perfectly happy with JavaScript. That's all.

**Comment by wookieb** [comment]
I know. That's why I'm not insisting anymore.

**Comment by zixia** [comment]
Hi all,

In the past 12 months, we had faced lots of issues with the TypeScript type definition, but it had not fixed well and the users still cannot work with the right typings after we spent lots of time on it (thanks @MeirionHughes , et al)

Rewriting to TypeScript will fix this problem. However, @vweevers is very happy with the JavaScript and always against to do that.

After some thoughts, I think we have a new direction to make everyone happy.

In short: **let's create a new npm module that supports TypeScript natively.**

The following will be my purposal:

1. Create a new repository, like: `level/levelmap`
1. `levelmap` will use `levelup` as its backend, expost all API as a ES6-Map-like
1. Develop in TypeScript
1. publish to npm as `levelmap`, and suggest TypeScript users to use this module.

The above is my 2-cents, please feel free to contribute any good ideas. If we can get a agreement about it, then I'd like to create the repository, develop it(with portional collabrators like @wookieb ), and publish it to npm as a `level` alternative for TypeScript users.

P.S. Actually, I had already build a module like what I had purposed at here, I used it for more than a year and it can fullfil all my requirements. See: <https://github.com/zixia/flash-store>

**Comment by vweevers** [comment]
> the users still cannot work with the right typings after we spent lots of time on it 

I believe it simply isn't done yet? Someone has to see it through, instead of changing direction (again). 

As @danwbyrne said (emphasis and applause mine):

> The ONLY Level packages that have actually been transferred from Level/Typings as of now are abstract-leveldown and level-codec **with the rest to follow in the coming weeks.** 👏

**Comment by danwbyrne** [comment]
Okay! All of the types in https://github.com/level/typings have been at least PR'd to DefinitelyTyped. If you want to track them all in one place here they are:

- [abstract-leveldown](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28411)
- [level-codec](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28431)
- [memdown](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28832)
- [levelup/leveldown](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28956)
- [encoding-down](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28958)
-[rocksdb](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28962)

I still don't fully support the way these are typed, but I unfortunately don't have the spare time right now to go through them all. You can see I change the pattern of the declarations on `encoding-down` and `rocksdb` which is how I think they should all look honestly.

I'll continue to monitor the repos if anyone else decides to contribute to the types, but that does it for me here :)

**Comment by vweevers** [comment]
Many thanks @danwbyrne!

**Comment by MeirionHughes** [comment]
Just had another look at typing this beast... typescript still can't deal with inferring derived generic parameters. i.e. :

```
type InferKey<DB> = DB extends Abstract<infer K, any> ?
  K :
  any;

interface Abstract<K = any, V = any> {
}

interface SpecialDB<K, V> extends Abstract<K, V>{
}

let db: SpecialDB<string, Buffer>;
let up: InferKey<typeof db>; // unknown type

```

**Comment by reuzel** [comment]
The error in the callback of the level(up) get operation should be extended. Typescript complains that the 'notFound' or 'type' properties do not exist on plain Error objects. You would need that to check if there is actual failure or if the record is simply not found in the database...
