### ISSUE TITLE
Add and remove npm owners

### ISSUE THREAD

**Issue by vweevers** [Level/community#17]
I've avoided `@mentioning` owners who are not (currently) active here, except when they are the sole owners or if already mentioned in this thread or a previous edit. For packages that are (to be) archived, we're more aggressive with removing owners.

- [x] leveldown
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] memdown
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @mafintosh
  - [x] Remove: @juliangruber 
  - [x] Remove: nolanlawson
- [x] abstract-leveldown
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] level-rocksdb
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] OK: @mcollina 
  - [x] Remove: @juliangruber
- [x] rocksdb
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] OK: @mcollina 
  - [x] Remove: @juliangruber
- [x] leveldown-hyper
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber
  - [x] Remove: hij1nx
- [x] levelup
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] level-iterator-stream
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK (bus factor): @juliangruber 
- [x] level-ws
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] level
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber
- [x] encoding-down
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK (bus factor): @juliangruber 
- [x] level-errors
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK (bus factor): @juliangruber 
- [x] level-packager
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] deferred-leveldown
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] level-ttl
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] level-codec
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK (bus factor): @juliangruber 
- [x] level-hyper
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] level-mem
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
- [x] level-test
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK (bus factor): @mcollina
  - [x] Remove: @juliangruber 
- [x] level-js
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK (bus factor): @mcollina
  - [x] Remove: @juliangruber 
  - [x] Remove: jameskyburz
  - [x] Remove: nolanlawson
  - [x] Remove: maxogden
- [x] subleveldown
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @mafintosh 
  - [x] Remove: @juliangruber 
- [x] level-concat-iterator
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK (bus factor): @juliangruber 
- [x] level-browserify (archived)
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
  - [x] Remove: @mcollina
  - [x] Remove: @mafintosh
- [x] level-lazy-open (archived)
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] Remove: @juliangruber 
- [x] level-mobile (to be archived)
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
  - [x] OK: @rvagg
  - [x] Remove: @juliangruber 
  - [x] Remove: @obastemur
- [ ] leveldown-mobile (to be archived)
  - [ ] Remove: @obastemur
  - [ ] Missing: @ralphtheninja
  - [ ] Missing: @vweevers
- [ ] level-fstream (to be archived)
  - [ ] Remove: @jcrugzz
  - [ ] Missing: @ralphtheninja
  - [ ] Missing: @vweevers
- [x] level-lmdb (archived)
  - [x] OK: @rvagg
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers
- [x] level-basho (archived)
  - [x] OK: @ralphtheninja
  - [x] OK: @vweevers

**Comment by ralphtheninja** [comment]
Nice work! I'll start fixing ownership to @juliangruber and @vweevers wherever I can.

**Comment by ralphtheninja** [comment]
Updated.

At time of writing the following repos/modules are left:

* `level-test`
* `leveldown-mobile`
* `level-lmdb`
* `level-fstream`

Not very active modules so not a big deal atm.

**Comment by vweevers** [comment]
Awesome, thanks!

**Comment by vweevers** [comment]
@mcollina can you add @ralphtheninja or me to `level-test`? Would like to release v3 soon.

**Comment by mcollina** [comment]
level-test is done.

**Comment by ralphtheninja** [comment]
Updated `subleveldown`.

**Comment by vweevers** [comment]
Updated the list above to be about removing inactive owners as well.

@Level/core If you see your name listed here as `TBD`, please let us know of which package(s) you'd like to remain owner. Likewise if you feel you've been wrongly listed as `Remove`. Note that ownership is about your _current_ investment: whether you're able to respond in a timely manner should issues arise. We can always restore your ownership in the future. Thanks!

**Comment by vweevers** [comment]
Done. Left are `level-fstream` and `leveldown-mobile`, those are tracked in https://github.com/Level/level-fstream/issues/66 and https://github.com/Level/leveldown-mobile/issues/18.
