### ISSUE TITLE
Create SauceLabs OSS accounts

### ISSUE THREAD

**Issue by vweevers** [Level/community#18]
As I wrote [here](https://github.com/Level/abstract-leveldown/issues/123#issuecomment-366503169):

> It turns out that you can have only 1 subaccount, and it isn't public. Not all that useful.
> So we'll need separate Sauce Labs accounts for each repo. We can however reuse our gmail address, with aliases. E.g. for the memdown account we'll use leveldb.org+memdown@, for abstract-leveldown we use leveldb.org+abstract.leveldown@, etc.

Might be easier to do this in one go. For:

- [x] `memdown` (previously used the main gmail address)
  - [x] Create account
    - [x] Username: `level-ci`
    - [x] Email: `leveldb.org+memdown@`
  - [x] Activate OSS
  - [x] Setup Travis and `airtap`
  - [x] Remove JWT Addon (https://github.com/Level/memdown/issues/133) (https://github.com/Level/memdown/pull/148)
- [ ] `level-test` (https://github.com/Level/level-test/issues/62)
  - [x] Create account
    - [x] Username: `level-test`
    - [x] Email: `leveldb.org+level.test@`
  - [x] Activate OSS
  - [ ] Setup Travis and `airtap`
- [x] `abstract-leveldown` (https://github.com/Level/abstract-leveldown/issues/123)
  - [x] Create account
    - [x] Username: `abstract-leveldown`
    - [x] Email: `leveldb.org+abstract.leveldown@`
  - [x] Activate OSS
  - [x] Setup Travis and `airtap`
- [ ] `level-packager`
  - [x] Create account
     - [x] Username: `level-packager`
     - [x] Email: `leveldb.org+level.packager@`
  - [x] Activate OSS
  - [ ] Setup Travis and `airtap`
- [x] `levelup`
  - [x] Create account
     - [x] Username: `levelup`
     - [x] Email: `leveldb.org+levelup@`
  - [x] Activate OSS
  - [x] Setup Travis and `airtap`
- [x] `level-js` (https://github.com/Level/level.js/issues/44)
  - [x] Create account
     - [x] Username: `level-js`
     - [x] Email: `leveldb.org+level.js@`
  - [x] Activate OSS
  - [x] Setup Travis and `airtap`

And at a later time, maybe also:

- `level-browserify`
- `level-mem`
- `encoding-down`
- `deferred-leveldown`
- `level-codec`
- `level-errors`
- `level-iterator-stream`
- `level-ws`

**Comment by ralphtheninja** [comment]
This will be awesome!

**Comment by vweevers** [comment]
Accounts created and activation email sent.

**Comment by ralphtheninja** [comment]
@vweevers I feel `levelup` has the highest priority right now, before `level-packager`.

**Comment by vweevers** [comment]
Agree

**Comment by vweevers** [comment]
`levelup` is done, `level-packager` is next but let's do that after we finish this round of releases.

**Comment by vweevers** [comment]
https://github.com/Level/community/issues/117
