### ISSUE TITLE
add yourselves

### ISSUE THREAD

**Issue by juliangruber** [Level/community#2]
Please add yourselves to this, as it will be used to automate npm ownership, readme creation and possibly more.

- [x] @chesles
- [x] @raynos
- [x] @dominictarr
- [x] @maxogden
- [x] @kesla
- [x] @hij1nx
- [x] @No9
- [x] @mcollina
- [x] @pgte
- [ ] @substack
- [x] @jcrugzz

**Comment by mcollina** [comment]
Done!

**Comment by dominictarr** [comment]
I'm confused? do i just need to click my checkbox?

**Comment by chesles** [comment]
@dominictarr add your info the the `community.json` file, then click your checkbox :)

**Comment by dominictarr** [comment]
ah, got it

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
@obastemur Feel free to add yourself. Make a PR and update package.json and https://github.com/level/community#contributors

**Comment by obastemur** [comment]
@ralphtheninja thanks!
