### ISSUE TITLE
Add missing people and metadata

### ISSUE THREAD

**Issue by vweevers** [Level/community#20]
- [x] Add mastodon handle for @ralphtheninja
- [x] Add @nolanlawson (who uses mastodon IIRC)
- [x] Add @vweevers
- [x] Add @shama
- [x] Add @qs44
- [x] "Maxwell ogden" => "Maxwell Ogden" - or "Max Ogden"? @maxogden 

Ref https://github.com/Level/level-js/pull/141.

- [x] hij1nx twitter => hxoht twitter
- [x] add substack
- [x] add Ryan Ramage
- [x] add James Kyburz
- [x] add Yoshua Wuyts
- [x] add Calvin Metcalf
- [x] add Nicholas Westlake
- [x] add Bryce Baril

**Comment by vweevers** [comment]
```
> level-js@3.0.0-rc1 remark
> remark README.md CONTRIBUTORS.md -o

CONTRIBUTORS.md
  1:1  warning  no social profile for @shama             social           remark-gh-contributors
  1:1  warning  no social profile for @vweevers          social           remark-gh-contributors
  1:1  warning  no social profile for @calvinmetcalf     social           remark-gh-contributors
  1:1  warning  no social profile for @substack          social           remark-gh-contributors
  1:1  warning  no social profile for @ralphtheninja     social           remark-gh-contributors
  1:1  warning  no social profile for @nrw               social           remark-gh-contributors
  1:1  warning  no social profile for @ryanramage        social           remark-gh-contributors
  1:1  warning  no social profile for @qs44              social           remark-gh-contributors
  1:1  warning  no social profile for @JamesKyburz       social           remark-gh-contributors
  1:1  warning  no social profile for @brycebaril        social           remark-gh-contributors
  1:1  warning  no social profile for @yoshuawuyts       social           remark-gh-contributors
  1:1  warning  no social profile for @nolanlawson       social           remark-gh-contributors
```

**Comment by vweevers** [comment]
When contributors are sourced from `git` rather than the Github API, we have a lot more missing metadata. Current output (for `level-js`):

---

# Contributors

| Name                    | GitHub                                                 | Social                                                        |
| ----------------------- | ------------------------------------------------------ | ------------------------------------------------------------- |
| **Vincent Weevers**     |                                                        |                                                               |
| **Maxwell ogden**       | [**@maxogden**](https://github.com/maxogden)           | [**@maxogden@twitter**](https://twitter.com/maxogden)         |
| **Lars-Magnus Skog**    | [**@ralphtheninja**](https://github.com/ralphtheninja) |                                                               |
| **Max Ogden**           |                                                        |                                                               |
| **Rod Vagg**            |                                                        |                                                               |
| **Nolan Lawson**        |                                                        |                                                               |
| **qs44**                |                                                        |                                                               |
| **Julian Gruber**       | [**@juliangruber**](https://github.com/juliangruber)   | [**@juliangruber@twitter**](https://twitter.com/juliangruber) |
| **Dominic Tarr**        | [**@dominictarr**](https://github.com/dominictarr)     | [**@dominictarr@twitter**](https://twitter.com/dominictarr)   |
| **Matteo Collina**      |                                                        |                                                               |
| **Kyle Robinson Young** |                                                        |                                                               |
| **Mathias Buus**        | [**@mafintosh**](https://github.com/mafintosh)         | [**@mafintosh@twitter**](https://twitter.com/mafintosh)       |
| **James Halliday**      |                                                        |                                                               |
| **Ryan Ramage**         |                                                        |                                                               |
| **James Kyburz**        |                                                        |                                                               |
| **Yoshua Wuyts**        |                                                        |                                                               |
| **Calvin Metcalf**      |                                                        |                                                               |
| **Nicholas Westlake**   |                                                        |                                                               |
| **Bryce Baril**         |                                                        |                                                               |

**Comment by vweevers** [comment]
Sec, let me run it against your `update-contributors` branch @ralphtheninja.

**Comment by vweevers** [comment]
Updated.

**Comment by ralphtheninja** [comment]
Noticed there are two Max. One `'Maxwell ogden'` and one `'Max Ogden'`. Updated.

**Comment by vweevers** [comment]
> Noticed there are two Max. One 'Maxwell ogden' and one 'Max Ogden'

That's because max shows up with two email adresses in git history. So do others.

**Comment by vweevers** [comment]
OK, if I also match by name (which I prefer to avoid but I also want to move on) it's better:

| Name                    | GitHub                                                 | Social                                                          |
| ----------------------- | ------------------------------------------------------ | --------------------------------------------------------------- |
| **Vincent Weevers**     | [**@vweevers**](https://github.com/vweevers)           | [**@vweevers@twitter**](https://twitter.com/vweevers)           |
| **Max Ogden**           | [**@maxogden**](https://github.com/maxogden)           | [**@maxogden@twitter**](https://twitter.com/maxogden)           |
| **Lars-Magnus Skog**    | [**@ralphtheninja**](https://github.com/ralphtheninja) | [**@ralph@social.weho.st**](https://social.weho.st/ralph)       |
| **Rod Vagg**            | [**@rvagg**](https://github.com/rvagg)                 | [**@rvagg@twitter**](https://twitter.com/rvagg)                 |
| **Nolan Lawson**        | [**@nolanlawson**](https://github.com/nolanlawson)     | [**@nolan@toot.cafe**](https://toot.cafe/nolan)                 |
| **Josh**                | [**@qs44**](https://github.com/qs44)                   |                                                                 |
| **Julian Gruber**       | [**@juliangruber**](https://github.com/juliangruber)   | [**@juliangruber@twitter**](https://twitter.com/juliangruber)   |
| **Dominic Tarr**        | [**@dominictarr**](https://github.com/dominictarr)     | [**@dominictarr@twitter**](https://twitter.com/dominictarr)     |
| **Matteo Collina**      | [**@mcollina**](https://github.com/mcollina)           | [**@matteocollina@twitter**](https://twitter.com/matteocollina) |
| **Kyle Robinson Young** | [**@shama**](https://github.com/shama)                 | [**@shamakry@twitter**](https://twitter.com/shamakry)           |
| **Mathias Buus**        | [**@mafintosh**](https://github.com/mafintosh)         | [**@mafintosh@twitter**](https://twitter.com/mafintosh)         |
| **James Halliday**      |                                                        |                                                                 |
| **Ryan Ramage**         |                                                        |                                                                 |
| **James Kyburz**        |                                                        |                                                                 |
| **Yoshua Wuyts**        |                                                        |                                                                 |
| **Calvin Metcalf**      |                                                        |                                                                 |
| **Nicholas Westlake**   |                                                        |                                                                 |
| **Bryce Baril**         |                                                        |                                                                 |

**Comment by vweevers** [comment]
Fixed.

**Comment by ralphtheninja** [comment]
@vweevers This one can be closed?
