### ISSUE TITLE
Export contributors as array instead of object

### ISSUE THREAD

**Issue by vweevers** [Level/community#22]
So that we're less tied to GitHub, and match the format used in `package.json` contributors.

WDYT @ralphtheninja?

**Comment by ralphtheninja** [comment]
SGTM!

**Comment by ralphtheninja** [comment]
@vweevers So array of objects with `name`, `email` and `url` (which is `homepage` atm)? https://docs.npmjs.com/files/package.json#people-fields-author-contributors

**Comment by vweevers** [comment]
+1 to renaming `homepage`, but let's keep the other properties (npm doesn't care if you put such properties in `package.json`, either). And add `github` (and then `mastodon`, `bitbucket`, `gitlab`, etc).
