### ISSUE TITLE
Break down thread in level/database into issues

### ISSUE THREAD

**Issue by ralphtheninja** [Level/community#28]
I forgot we have an empty repository here https://github.com/Level/database, but it has an interesting thread here https://github.com/Level/database/issues/1

I'd like to remove the repository but keep the issue thread in this repository. Possible?

**Comment by vweevers** [comment]
There are tools to move issues but you loose formatting etc. Alternatively, we can break down that thread into actionable issues (here), then archive `database`.

**Comment by vweevers** [comment]
> philosophical goal?
> to present answers to common on boarding questions with a working example of "database" that works as a database for databasing.

> \[we are missing\] a 'full feature' database

> this sounds more like we need documentation and examples of how to solve genuine non-trivial use cases with leveldb & level- modules at scale.

- Write tutorials for real world use cases: https://github.com/Level/community/issues/88
- Write FAQ: https://github.com/Level/community/issues/78

> we should put it as the main website for level, citing the most common options

We'll keep that in mind when working on the above tickets.

> \[we are missing\] a web playgroung in redis style

https://github.com/Level/leveljs.org/issues/49
