### ISSUE TITLE
State of documentation

### ISSUE THREAD

**Issue by ralphtheninja** [Level/community#29]
The state of `README.md` (style updated with level badge etc), `CHANGELOG.md` and `UPGRADING.md`.

EDIT (@ralphtheninja): Updated with `LICENSE.md/CONTRIBUTORS.md/README.md` which essentially means "There is a `LICENSE.md` file and a `CONTRIBUTORS.md` file, where `LICENSE.md` links to `CONTRIBUTORS.md` and `README.md` links to `LICENSE.md` according to new and simplified format in https://github.com/Level/level-js/tree/ce8d77c89f38e444b6951e890aa3b5e72a221aaf#license"

EDIT (@vweevers): Added tasks to remove `contributors` from `package.json` and to remove copyright headers from code.

Below is a summary of all repositories. Some of these are not actively maintained and some might be more or less irrelevant for other reasons, e.g. maybe we don't need `UPGRADING.md` for `electron-demo` etc.

Please comment and/or edit this post if you think that something should be archived or need special care.

- [x] `abstract-leveldown`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `awesome`
  - [x] `README.md` (needs to be re-generated after `level-js` and `level-browserify`)
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `codec`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `concat-iterator`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `community`
  - [x] `README.md`
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `deferred-leveldown`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `electron-demo`
  - [x] `README.md`
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `encoding-down`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `errors`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `iterator-stream`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `leveldb.org`
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `leveldown`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `leveldown-hyper`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-hyper`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-js`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-test`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-rocksdb`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [ ] `level-ttl`
  - [ ] `README.md`
  - [ ] `CHANGELOG.md`
  - [ ] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `levelup`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-ws`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `mem`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `memdown`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `packager`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `rocksdb`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `subleveldown`
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `lazy-open` (archived)
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~ `UPGRADING.md`~~
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-lmdb` (to be archived)
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-mobile` (to be archived)
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `leveldown-mobile` (to be archived)
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-fstream` (to be archived)
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-basho` (archived)
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `level-browserify` (archived)
  - [x] `README.md`
  - [x] `CHANGELOG.md`
  - [x] `UPGRADING.md`
  - [x] `LICENSE.md/CONTRIBUTORS.md/README.md`
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `typings` (archived)
  - [x] `README.md`
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] Remove `contributors` from `package.json`
  - [x] Remove copyright headers from code
- [x] `database` (archived)
  - [x] ~~`README.md`~~
  - [x] ~~`CHANGELOG.md`~~
  - [x] ~~`UPGRADING.md`~~
  - [x] ~~`LICENSE.md/CONTRIBUTORS.md/README.md`~~
  - [x] ~~Remove `contributors` from `package.json`~~
  - [x] ~~Remove copyright headers from code~~

**Comment by vweevers** [comment]
+1 to archiving not actively maintained repos

**Comment by vweevers** [comment]
Except for `typings`, as I understand it that's a temporary home for typescript, and a work-in-progress.

**Comment by ralphtheninja** [comment]
I think we should at least tweak the README of not actively maintained before archiving, it's quickly done.

**Comment by ralphtheninja** [comment]
Lets make another pass at this later with `LICENSE.md` (which should link to ->) and `CONTRIBUTORS.md`.

**Comment by ralphtheninja** [comment]
Updated.

**Comment by vweevers** [comment]
@ralphtheninja as part of this effort, should we also:

1. Remove `contributors` from `package.json`
2. Remove copyright headers from JS files

I think yes. See https://github.com/Level/levelup/pull/587#issuecomment-397836395.

**Comment by ralphtheninja** [comment]
> @ralphtheninja as part of this effort, should we also:
> 
>     Remove contributors from package.json
>     Remove copyright headers from JS files
> 
> I think yes. See Level/levelup#587 (comment).

Agreed.

**Comment by vweevers** [comment]
Added.

**Comment by ralphtheninja** [comment]
Funny enought, `leveldown-hyper` is the first project to tick all boxes :smile:

**Comment by ralphtheninja** [comment]
I ticked the boxes for irrelevant tasks, just to see the progress and what's _really_ left to do.

**Comment by ralphtheninja** [comment]
Will finish `level-hyper`, `encoding-down` and `electron-demo` next.

**Comment by ralphtheninja** [comment]
I archived the `database` repository.

**Comment by ralphtheninja** [comment]
@vweevers I'm going to refer to `LICENSE.md/CONTRIBUTORS.md/README.md` as `hallmark` from now on, so if you see issues created mentioning `hallmark`, this is what I mean.

**Comment by vweevers** [comment]
Ticked `typings`.

**Comment by vweevers** [comment]
`remark-cli` had a major release but I couldn't see what changed at first glance. Dumping a list of greenkeeper PR's:

- [ ] https://github.com/Level/leveldown/pull/520
- [ ] https://github.com/Level/electron-demo/pull/97
- [ ] https://github.com/Level/leveldown-hyper/pull/81
- [ ] https://github.com/Level/level-browserify/pull/62
- [ ] https://github.com/Level/level-hyper/pull/36
- [ ] https://github.com/Level/packager/pull/75
- [ ] https://github.com/Level/levelup/pull/614
- [ ] https://github.com/Level/encoding-down/pull/69

**Comment by vweevers** [comment]
I'm writing a script to do some of the above automatically across the board.

**Comment by vweevers** [comment]
Progress:

- [x] Create branch
- [x] Sort `package.json`
- [x] Add `repository` and `homepage` to `package.json`
- [x] Add `'level'` to `keywords`
- [x] Add or upgrade `hallmark`
- [x] Add or upgrade `level-community`
- [x] Remove `remark-*` dependencies, `remarkConfig` and `remark` npm script
- [x] Add md file(s) to `hallmark.ignore` if they contain `<a`
- [x] Add `hallmark --fix` npm script
- [x] Add `hallmark` to npm test script
- [x] Add `CONTRIBUTORS.md`
- [x] Rename `LICENSE` file to `LICENSE.md` with standard format
- [x] Fix copyright year to be `Math.min(current, initialCommitYear)`
- [x] Update `Licen(s|c)e`  heading in `README.md`
- [ ] Add `License` heading if missing
- [ ] Exclude `leveldown` to keep LevelDB and Snappy credits
- [x] Run `hallmark --fix`
- [ ] Push branch

Manual tweaks left:

- [ ] Remove `Contributors` section from `deferred-leveldown` readme

**Comment by vweevers** [comment]
@ralphtheninja prepare yourself for 28 PRs 😄

**Comment by vweevers** [comment]
Adding another automated step to fix the frequently occuring `Do not use upper-case characters in definition labels`.

**Comment by vweevers** [comment]
231 of 245 tasks done!

**Comment by vweevers** [comment]
Sure

**Comment by vweevers** [comment]
Only two more to go: `errors` and `level-ttl`.

**Comment by vweevers** [comment]
Closing because for the 1 remaining task we have https://github.com/Level/level-ttl/pull/108.
