### ISSUE TITLE
Standard status

### ISSUE THREAD

**Issue by ralphtheninja** [Level/community#35]
- [x] level-fstream
- [x] lazy-open
- [x] level-ttl
- [x] abstract-leveldown
- [x] awesome
- [x] codec
- [x] concat-iterator
- [x] deferred-leveldown
- [x] electron-demo
- [x] encoding-down
- [x] errors
- [x] iterator-stream
- [x] level
- [x] level-browserify
- [x] leveldown
- [x] leveldown-hyper
- [x] level-hyper
- [x] level-js
- [x] level-rocksdb
- [x] level-test
- [x] levelup
- [x] level-ws
- [x] mem
- [x] memdown
- [x] packager
- [x] rocksdb
- [x] subleveldown
- [x] ~~leveldown-mobile~~
- [x] ~~level-mobile~~
- [x] ~~level-basho~~
- [x] ~~level-lmdb~~

**Comment by ralphtheninja** [comment]
I scratched `leveldown-mobile`, `level-mobile`, `level-basho` and `level-lmdb` for now, since they aren't actively maintained.

`lazy-open` and `level-fstream` left!

**Comment by ralphtheninja** [comment]
Actually, I think I'm going for `lazy-open` and `level-fstream` to have less balls to juggle and we can be done with standard.

**Comment by vweevers** [comment]
@ralphtheninja nice work and congrats! Great to have `standard` across the board.
