### ISSUE TITLE
Add dependency-check to all repositories

### ISSUE THREAD

**Issue by ralphtheninja** [Level/community#36]
- [x] abstract-leveldown
- [x] awesome
- [x] codec
- [x] community
- [x] concat-iterator
- [x] ~~database~~
- [x] deferred-leveldown
- [x] electron-demo
- [x] encoding-down
- [x] errors
- [x] iterator-stream
- [x] lazy-open
- [x] level
- [x] level-browserify
- [x] leveldb.org
- [x] leveldown
- [x] leveldown-hyper
- [x] level-hyper
- [x] level-js
- [x] level-rocksdb
- [x] level-test
- [x] level-ttl
- [x] levelup
- [x] level-ws
- [x] mem
- [x] memdown
- [x] packager
- [x] rocksdb
- [x] subleveldown

**Comment by vweevers** [comment]
Personal request: not before fixing Windows compat in `dependency-check`, please :)

**Comment by ralphtheninja** [comment]
Lets fix `dependency-check` first then :wink:

**Comment by vweevers** [comment]
https://github.com/maxogden/dependency-check/pull/93

**Comment by ralphtheninja** [comment]
Released in https://github.com/maxogden/dependency-check/releases/tag/v3.2.0

**Comment by vweevers** [comment]
Nice!

**Comment by ralphtheninja** [comment]
> @ralphtheninja do you want to add `npm run dependency-check` to the `test` script, or `prepublishOnly`?

I have no strong opinion. Do what feels best to you :)

**Comment by vweevers** [comment]
I'm leaning towards `prepublishOnly` because dependencies don't change that often, so I'll go with that.

Also I think I prefer to skip `--unused`, there are too many devDependencies to ` --ignore`.
