### ISSUE TITLE
Remove email notifications from all Travis setups?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/community#40]
Also, do we really need `sudo: false` anymore?

**Comment by vweevers** [comment]
I wouldn't mind, esp. with all the random failures lately. It's crazy

**Comment by vweevers** [comment]
Also I used to rely on these emails for progress updates but now I just look at the project board.

**Comment by ralphtheninja** [comment]
Maybe we could use a level-mail which redirects? I have a feeling it's causing quite a lot of spam for people in @Level/core

**Comment by vweevers** [comment]
Sure, we could send it to `leveldb.org+travis@` - if there's anyone left who wants these notifications.

**Comment by vweevers** [comment]
@ralphtheninja I'm gonna start disabling notifications, in the noisiest repos. Without email forwarding.

Note that Travis only sends emails to [the committer and the author](https://docs.travis-ci.com/user/notifications/#how-is-the-build-email-receiver-determined) so other people aren't spammed. But we (active maintainers) are. There are maybe a few scenarios where notifications are useful, but those notifications currently get lost in the noise anyway.

**Comment by vweevers** [comment]
- [ ] [`level-ttl`](https://github.com/Level/level-ttl)
- [ ] [`leveldown`](https://github.com/Level/leveldown)
- [ ] [`memdown`](https://github.com/Level/memdown)
- [ ] [`rocksdb`](https://github.com/Level/rocksdb)
- [ ] [`level-js`](https://github.com/Level/level-js)
- [ ] [`abstract-leveldown`](https://github.com/Level/abstract-leveldown)
- [ ] [`level`](https://github.com/Level/level)
- [ ] [`levelup`](https://github.com/Level/levelup)
- [ ] [`deferred-leveldown`](https://github.com/Level/deferred-leveldown)
- [ ] [`encoding-down`](https://github.com/Level/encoding-down)
- [ ] [`concat-iterator`](https://github.com/Level/concat-iterator)
- [ ] [`errors`](https://github.com/Level/errors)
- [ ] [`mem`](https://github.com/Level/mem)
- [ ] [`level-ws`](https://github.com/Level/level-ws)
- [ ] [`bench`](https://github.com/Level/bench)
- [ ] [`codec`](https://github.com/Level/codec)
- [ ] [`compose`](https://github.com/Level/compose)
- [ ] [`iterator-stream`](https://github.com/Level/iterator-stream)
- [ ] [`level-test`](https://github.com/Level/level-test)
- [ ] [`level-rocksdb`](https://github.com/Level/level-rocksdb)
- [ ] [`packager`](https://github.com/Level/packager)
- [ ] [`subleveldown`](https://github.com/Level/subleveldown)
- [ ] [`level-hyper`](https://github.com/Level/level-hyper)
- [ ] [`leveldown-hyper`](https://github.com/Level/leveldown-hyper)
- [ ] [`leveljs.org`](https://github.com/Level/leveljs.org)
- [ ] [`community`](https://github.com/Level/community)
- [ ] [`electron-demo`](https://github.com/Level/electron-demo)
- [ ] [`browserify-starter`](https://github.com/Level/browserify-starter)
- [ ] [`webpack-starter`](https://github.com/Level/webpack-starter)
- [ ] [`awesome`](https://github.com/Level/awesome)

**Comment by vweevers** [comment]
![image](https://user-images.githubusercontent.com/3055345/66254535-ca241e80-e777-11e9-81c5-465a98bc72e8.png)

^ Proof that we're right to disable them 🤣

**Comment by vweevers** [comment]
Done.
