### ISSUE TITLE
Migrate to lerna

### ISSUE THREAD

**Issue by wookieb** [Level/community#41]
With monorepo would be easier to maintain dependencies and fix related issues.

**Comment by vweevers** [comment]
Having used monorepos in the past, I disagree. They:

1. Make versioning, prebuilds, installation and forking harder
1. Assume that all maintainers are familiar with all projects
1. Increase notification noise
1. Blur the boundaries between modules
1. Increase the chance of violating the single responsibility principle.

**Comment by wookieb** [comment]
1. Versioning - Lerna allows for independent versioning. 
Installation - with lerna is super easy and allows to raise common dev dependencies level higher. Forking - what real obstacle do you see here?

2. Why? In order to fix one project you just go to one particular directory with a package.

3. True. Minor issue for me.

4. No. IMHO the boundaries and too tight right now (for example encoding-down and level-codec or level and level-packaging)

5. That's why we have Pull requests. You won't prevent making stupid mistakes either way.

**Comment by vweevers** [comment]
> Lerna allows for independent versioning

Sure, it has that feature. Does not mean that versioning is independent in practice. You end up with a big bag of prefixed git tags, which IMO leads to cognitive overhead. In addition, any tooling (other than lerna) has to be modified to support these tags.

We have a fairly clean setup for prebuilds and CI atm. I can't imagine it'd be the same in a monorepo. For example, we'd very quickly hit concurrency limits on Travis/AppVeyor/Sauce Labs builds.

> Forking - what real obstacle do you see here?

Right now it's easy to fork one project and start hacking on it. If you instead have to pull a monorepo, you first have to familiarize yourself with `lerna`, the project structure, etc.

> IMHO the boundaries and too tight right now (for example encoding-down and level-codec or level and level-packaging)

Could you elaborate?

> That's why we have Pull requests. You won't prevent making such stupid mistakes either way.

I'm not talking about "stupid" mistakes. When code is too close together, you slowly start to treat it as one module, and lose sight of individual responsibilities. When modules are "physically" separated, I find it easier to keep them separated mentally as well.

**Comment by ralphtheninja** [comment]
> In any case, it's a big -1 for me. What do you think, @ralphtheninja?

Call me an old fart, but I think what we have right now works very well and I don't see the big advantage(s). It seems to me it's modules versus frameworks discussion and I think it's pretty clear what the level devs opinion is on this matter.
