### ISSUE TITLE
Address security concerns from community

### ISSUE THREAD

**Issue by vweevers** [Level/community#43]
**In light of the recent `event-stream` incident, we (@ralphtheninja  and I) want to take action to reduce the attack surface of packages maintained in Level.**

Level has been and will remain an OPEN Open Source Project. While we recognize the risk of giving people owner rights, it has been vital to the open, transparent and dare I say _loving_ nature of Level. We might add _some_ policy, if it really benefits security. Keep in mind that too much policy can scare off contributors, put a burden on maintainers and provide a false sense of security, hiding real issues that are out of our control under a layer of bureaucracy that in addition impedes individual freedom.

Trust is essential in OSS and we want to be wary of knee-jerk reactions to incidents like `event-stream`.

That said, we are thinking about what we can do and open to any suggestions. After an initial brainstorm we came up with 3 actionable items and wished to move further discussion to GitHub for community input and transparency.

## 1. Reduce npm owners

- [x] Our npm packages have more owners than needed for continued maintenance. Go through the list of current owners and ask if they _really_ want/need publish rights: #17.

## 2. Reduce GitHub organization owners

- [ ] We have quite a few inactive members. We will ask them if they can be removed and list removed members as Collaborator Emeriti in a suitable place.

## 3. Archive unmaintained projects

Archival consists of:

- Pinning dependencies (note: transient dependencies are out of our control)
- Releasing a final patch version
- Deprecating the package
- Removing extraneous npm owners
- Archiving the GitHub repository.

Candidates for archival:

- [x] [`leveldown-mobile`](https://github.com/Level/leveldown-mobile): https://github.com/Level/leveldown-mobile/issues/18
- [x] [`level-mobile`](https://github.com/Level/level-mobile):  https://github.com/Level/level-mobile/issues/17
- [x] [`level-lmdb`](https://github.com/Level/level-lmdb): https://github.com/Level/level-lmdb/issues/12
- [x] [`level-fstream`](https://github.com/Level/level-fstream): https://github.com/Level/level-fstream/issues/66
- [x] [`level-basho`](https://github.com/Level/level-basho): https://github.com/Level/level-basho/issues/13
- [x] [`level-lazy-open`](https://github.com/Level/lazy-open): https://github.com/Level/lazy-open/issues/42

Please edit the above list or leave a comment if you think one of these should not be archived.

**Comment by ralphtheninja** [comment]
`level-graveyard`? :)

**Comment by vweevers** [comment]
I think it's fine to keep the repos here. If someone comes forward wanting to revive a project, we can then decide whether to move the repo elsewhere or stay involved.

**Comment by vweevers** [comment]
What's a good message for `npm deprecate <pkg> <message>`?

1. `This project has been abandoned. There will be no further releases. If you wish to revive level-mobile, please open an issue (https://github.com/Level/community) to discuss a way forward. Thank you!` (similar to the [readme](https://github.com/Level/level-mobile/blob/abfaddefd9ccb22c452647de79b60e0b9023353e/README.md))
2. `This project has been abandoned. There will be no further releases.`
3. `This project has been abandoned. Please see the README for more information.`
4. `This project has been abandoned. Please visit GitHub for more information.`

**Comment by ralphtheninja** [comment]
I prefer the first one. It's nice to have a link to go to for more information.

**Comment by vweevers** [comment]
Hm, there's a downside to pinning dependencies of a package before abandoning it: when a dependency patches a vulnerability, it doesn't float in. You can't win..

**Comment by vweevers** [comment]
Should we archive [`level-lazy-open`](https://github.com/Level/lazy-open) as well? 0 downloads, 0 dependents, and superseded by `deferred-leveldown`.

**Comment by ralphtheninja** [comment]
> Should we archive level-lazy-open as well? 0 downloads, 0 dependents, and superseded by deferred-leveldown.

:ok:

**Comment by vweevers** [comment]
The remaining task (reduce GitHub organization owners) is being handled and discussed privately.
