### ISSUE TITLE
Beef up benchmark suite

### ISSUE THREAD

**Issue by juliangruber** [Level/community#46]
I'd like to drop the SQLite and Leveled bencharks, as we know we're faster than SQLite and also Leveled, as soon as #95 is done.

Then, add bencharks for all levelup features so we can test streams, encodings and more.

Are you cool with this?

**Comment by vweevers** [comment]
> So we're cool with 2 benchmark suites?
> 
> 1. bench every levelUp feature and compare between levelUp versions
> 2. compare levelUp with levelDB, redis, mysql, couch, and more. Here we can/should have both basic things and more real-life use cases. Like get and put but also "give me all the comments that belong to post X" and "fully replicate the database".

Splitting this up:

1. Move [`levelup` benchmarks](https://github.com/Level/levelup/tree/7e844aa9a4b0804437ab3bf4378c94a507efb937/test/benchmarks) to [`level-bench`](https://github.com/Level/bench) 🆕 (https://github.com/Level/levelup/issues/652)
1. Add benchmarks for other stores (done, as `level-bench` takes any)
1. Add (ability to compare against) C++ benchmarks (https://github.com/Level/bench/issues/1)
