### ISSUE TITLE
Create starter repository with level/browserify/webpack examples

### ISSUE THREAD

**Issue by vweevers** [Level/community#62]
Forked from https://github.com/Level/levelup/issues/619, cc @fergiemcdowall.

We can use [level-with-webpack-test](https://github.com/vweevers/level-with-webpack-test) as a starting point, maybe move the package to a subdirectory and add more subdirectories to demonstrate setups with `browserify` and others.

Or, create a starter repo for each? E.g. `Level/level-with-webpack-starter`.

**Comment by fergiemcdowall** [comment]
Yes, maybe a single repo like [level-with-webpack-test](https://github.com/vweevers/level-with-webpack-test) with a `script` command for every supported packaging tool: `npm run build-with-browserify`, `npm run build-with-webpack`, (and if we can get it to work) `npm run build-with-rollup` ?

BTW: things I like about level-with-webpack-test as it is now:

 * it is very terse, clear, and unpolluted by extraneous complications (test suites, linters, development servers, and other bells and whistles).
 * The source file is written in an ES6 style.

**Comment by vweevers** [comment]
> it is very terse, clear, and unpolluted by extraneous complications (test suites, linters, development servers, and other bells and whistles).

Yeah, that's why I'm leaning towards multiple starter repos (keeps dependencies and scripts clean). And `level-with-webpack-test` does have a linter atm (`standard`) but that was not intentional, we can remove it.

**Comment by vweevers** [comment]
(Side note: when creating `level-with-webpack-test`, which should have taken a minute, I wasted probably 15 minutes trying to understand `webpack(-cli)`. First I installed `webpack`, which comes with what seems to be a dummy CLI, and it told me to install `webpack-cli`, so I did and removed `webpack`, but `webpack-cli` complained it couldn't find `webpack`, so I did the `rm -rf node_modules && npm i` dance, still didn't work, then I installed both and it worked. Waaat is this nonsense)

**Comment by vweevers** [comment]
Poll time! How should we structure this?

[![](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/multiple%20repositories)](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/multiple%20repositories/vote)
[![](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/one%20monorepo%20with%20a%20nested%20package%20for%20each%20bundler)](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/one%20monorepo%20with%20a%20nested%20package%20for%20each%20bundler/vote)
[![](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/one%20repository%20with%20an%20npm%20script%20for%20each%20bundler)](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/one%20repository%20with%20an%20npm%20script%20for%20each%20bundler/vote)
[![](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/none%20of%20the%20above%20(e.g.%20write%20a%20guide%20instead))](https://api.gh-polls.com/poll/01D1GG9QT02HRGZ57M1EX0A17S/none%20of%20the%20above%20(e.g.%20write%20a%20guide%20instead)/vote)

**Comment by vweevers** [comment]
https://github.com/Level/webpack-starter

**Comment by vweevers** [comment]
https://github.com/Level/browserify-starter
