### ISSUE TITLE
How can I read a stream of operations?

### ISSUE THREAD

**Issue by christianbundy** [Level/community#64]
Apologies if this is in the wrong repo.

I'd like to be able to subscribe to a stream of operations on a levelup instance -- is that something that I can do, or is that something that would have to be supported by a given store? For example, I'd like to receive a list of all of the `put` or `del` operations, *especially* if I'm able to see the list of past operations.

Thanks!

**Comment by vweevers** [comment]
Feel free to reopen if you have further questions.
