### ISSUE TITLE
Migrate Travis to GitHub Apps for all repos

### ISSUE THREAD

**Issue by vweevers** [Level/community#67]
See https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/

**Comment by ralphtheninja** [comment]
> As of May 2, 2018 we are moving toward having repositories integrated via a GitHub App instead of GitHub Services which will no longer be supported by GitHub as of January 31st, 2019.

They stopped supporting it but it's working?

**Comment by vweevers** [comment]
Yeah.. I'm guessing they extended it because people (like us) are still using it?

**Comment by ralphtheninja** [comment]
Done

**Comment by ralphtheninja** [comment]
Actually, lets leave it open until we know everything works.

![Screenshot from 2019-05-20 12-47-47](https://user-images.githubusercontent.com/308049/58016276-8056d680-7afd-11e9-9df1-f0f6c992f4e6.png)

**Comment by ralphtheninja** [comment]
Oh, this is only about private repositories?

**Comment by vweevers** [comment]
It should also be disabled for some repos (like awesome)

**Comment by vweevers** [comment]
@ralphtheninja Maybe we should also remove Greenkeeper and Travis webhooks? Looking at a recent project with Greenkeeper integration (https://github.com/Level/webpack-starter/settings/hooks), it seems webhooks are not needed anymore. Maybe that's true for Travis as well.

**Comment by vweevers** [comment]
Ah, our repos are currently active on `travis-ci.org` (with according webhooks). The migration activated them on `travis-ci.com`. So the remaining tasks are:

- [ ] Copy secret env vars and configuration (if any) for every repo to `travis-ci.com`
- [ ] Disable a few repos in the GitHub App for `travis-ci.com` (`awesome`, `community`, `leveljs.org` and perhaps the archived ones)
- [ ] Remove old webhooks (Travis and Greenkeeper) from all repos
- [ ] Deactivate all repos on old `travis-ci.org`

**Comment by vweevers** [comment]
Task added: `Update badges in READMEs (org -> com)`.

**Comment by vweevers** [comment]
Repos (also listed archived ones, because "all or nothing" is easier to manage, i.e. we should end up with nothing in `travis-ci.org` and all in `travis-ci.com`):

- [x] `.github`
- [ ] `abstract-leveldown`
- [x] `awesome`
- [x] `bench`
- [ ] `browserify-starter`
- [ ] `codec`
- [x] `community`
- [x] `compose`
- [ ] `concat-iterator`
- [x] `database` (archived)
- [ ] `deferred-leveldown`
- [ ] `electron-demo`
- [ ] `encoding-down`
- [ ] `errors`
- [ ] `iterator-stream`
- [ ] `lazy-open` (archived)
- [ ] `level`
- [ ] `level-basho` (archived)
- [ ] `level-browserify` (archived)
- [ ] `level-fstream` (to be archived)
- [ ] `level-hyper`
- [ ] `level-js`
- [ ] `level-lmdb` (archived)
- [ ] `level-mobile` (archived)
- [ ] `level-test`
- [ ] `level-ttl`
- [ ] `level-rocksdb`
- [ ] `level-ws`
- [ ] `leveldown`
- [ ] `leveldown-hyper`
- [ ] `leveldown-mobile` (to be archived)
- [x] `leveljs.org`
- [ ] `levelup`
- [ ] `mem`
- [ ] `memdown`
- [ ] `packager`
- [ ] `rocksdb`
- [ ] `subleveldown`
- [x] `typings` (archived)
- [ ] `webpack-starter`

**Comment by vweevers** [comment]
I cannot figure out how to activate a repo on travis-ci.com after having disabled it on travis.ci.org. Perhaps that's just not supported.

It seems you have to sign up for a [beta](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) in order to migrate existing repos.

**Comment by vweevers** [comment]
I signed up for the beta.

**Comment by vweevers** [comment]
Travis migration done. Also removed old testling, greenkeeper, zenhub and waffle webhooks.

While I'm at it, lemme see if I can migrate AppVeyor to GitHub Apps too.

- [ ] [`level`](https://github.com/Level/level)
- [ ] [`leveldown`](https://github.com/Level/leveldown)
- [ ] [`rocksdb`](https://github.com/Level/rocksdb)

**Comment by vweevers** [comment]
Done.
