### ISSUE TITLE
Retire IRC channel?

### ISSUE THREAD

**Issue by vweevers** [Level/community#69]
It's been dead for a long time. It was used for the Google discussion recently, which made the channel seem active, and made me sign up for IRCCloud, but now it seems I'm the only one left. Though I don't mind dedicating time to it, questions and discussions would benefit from having multiple participants (both Level members and users).

@Level/core What do you say about retiring the channel? Or at the very least, update our documentation to point to GitHub, clarifying that it's totally cool to open support requests here?

**Comment by LewisAndrewCampbell** [comment]
I popped into the IRC channel today after spending the weekend re-writing some code to use levelup. The docs are pretty clear but I have a lot of questions about using embedded key value stores in anger, so I'll sign up to wherever.

**Comment by vweevers** [comment]
To clarify: I do _not_ want to start using Discord or Slack or any other secondary platform. GitHub all the way.

**Comment by ralphtheninja** [comment]
I don't mind retiring it.

**Comment by rvagg** [comment]
:+1:

**Comment by juliangruber** [comment]
I'm also in favor, it's hard to ensure a frustration-free experience
