### ISSUE TITLE
Update multileveldown and level-party

### ISSUE THREAD

**Issue by MattMorgis** [Level/community#71]
Hi,

I understand `leveldown@v5` is the minimum version for Node.js 12 support. 

Is it feasible to add Node.js 12 support to v4? I'd be happy to help out, but curious if it's a lost cause from the start. 

I ask because I am working on updating `level-party`. I was able to get it to run on Node.js 10 and 11 by having it use a combination of `levelup@1.x` and `leveldown@4.x` (from `leveldown@1.x`. 

It seems a refactor to `leveldown@5x` would require a refactor to `abstract-leveldown@v6` and `levelup@2.x+`, which has some changes to encodings. If it's possible to add Node.js 12 support to v4, I could avoid the big reactor for now.

**Comment by MattMorgis** [comment]
Tried it out here: https://github.com/MattMorgis/level-party/tree/node-10-support

Still getting the same error I mentioned above in `level-party`. It seems to get back the raw Buffer data back:
```
not ok 2 should be equivalent
  ---
    operator: deepEqual
    expected: [ 'a' ]
    actual:   <Buffer a0 70 61 00 00>
    at: ReadStream.<anonymous> (/Users/morgism/Developer/nodejs/level-modules/level-party/test/bytewise.js:27:15)
  ...
not ok 3 should be equivalent
  ---
    operator: deepEqual
    expected: 22319
    actual:   { data: [ 50, 50, 51, 49, 57 ], type: 'Buffer' }
    at: ReadStream.<anonymous> (/Users/morgism/Developer/nodejs/level-modules/level-party/test/bytewise.js:28:15)
```

**Comment by vweevers** [comment]
It might be helpful to copy (and adapt) that test to `multileveldown`. Then fix it there without `level-party` muddying the waters.

**Comment by binarykitchen** [comment]
Just scanned your conversations and salute your hard work to update both libraries. Really can't wait to upgrade these because Node.js v8 nears end-of-life this December, so ...

**Comment by vweevers** [comment]
Recent changes in `memdown` will make it easier to upgrade and test these. There's a few related releases to get out the door.

I'll move this task up in the [project board](https://github.com/orgs/Level/projects/2).

**Comment by binarykitchen** [comment]
@vweevers can I help with that somehow? To speeden up things?

**Comment by vweevers** [comment]
I don't remember all the details, but you could take this commit and attend the TODO comments: https://github.com/vweevers/multileveldown/commit/88e284d395f6d80403ad53e8a04bd6b22ef59dc3. I'll add some GitHub comments to that commit as well, for context.

**Comment by binarykitchen** [comment]
Sorry @vweevers I am more into level-party, want to make it work for Node.js v10

**Comment by vweevers** [comment]
`level-party` depends on `multileveldown`; getting `multileveldown` up to par is the first step.

**Comment by vweevers** [comment]
`multileveldown` is mostly complete: https://github.com/vweevers/multileveldown/commit/60772a7fac6ff96dd90ec158bfc85d57a98a8563

Moving on to `level-party`.

**Comment by vweevers** [comment]
Tests are passing: vweevers/level-party@d94eac3ff81954b2d17a028ac2d2735090b908b4.

More tweaks are likely needed to also make it work with `subleveldown`.

**Comment by vweevers** [comment]
- `subleveldown` on `level-party` works
- `subleveldown` on `multileveldown` client works (i.e. for client-side sublevels)
- `multileveldown` server on `subleveldown` works (i.e. to expose only a sublevel to client)

That last one surprises me, I'm gonna write more tests to try and break it.

**Comment by vweevers** [comment]
Opened https://github.com/mafintosh/multileveldown/pull/15 and https://github.com/substack/level-party/pull/20.

**Comment by binarykitchen** [comment]
@vweevers thanks so much! hope they will pass review, merged and published soon.

**Comment by vweevers** [comment]
`multileveldown` has moved to Level and is ready for release, just waiting for npm ownership.

**Comment by binarykitchen** [comment]
Cool, I'm getting excited ...

**Comment by vweevers** [comment]
`level-party@4` is out.
