### ISSUE TITLE
Add type property to levelup and abstract-leveldown implementations

### ISSUE THREAD

**Issue by vweevers** [Level/community#82]
A continuation of https://github.com/Level/subleveldown/issues/34. cc @ralphtheninja 

### Background

Modules like `subleveldown` and `multileveldown` have to peel off layers (`levelup`, `deferred-leveldown` and/or `encoding-down`) from an input db to get to the inner db, which they then rewrap with those same layers.

That process ain't pretty, so I wrote [`reachdown`](https://github.com/vweevers/reachdown/blob/master/index.js) to hide that ugliness. It currently has to feature-detect `deferred-leveldown` and `encoding-down`, and this may clash with another `abstract-leveldown` implementation at some point. To counter that, we can add a `type` property across the board:

```js
MyLeveldown.prototype.type = 'my-leveldown'
```

Note: with that in place, the unwrapping (or even merely the fact that we have to unwrap) still isn't very clean, but IMO it's acceptable as a medium-term solution because there's a plan to merge `level(up)` functionality into `abstract-leveldown` (https://github.com/Level/community/issues/58) which ultimately removes the need to unwrap.

#### Add `type`

- [x] `levelup`
  - [x] PR or commit: https://github.com/Level/levelup/pull/678
  - [x] Release: 4.3.0 
- [x] `deferred-leveldown`
  - [x] PR or commit: https://github.com/Level/deferred-leveldown/pull/75
  - [x] Release: 5.2.1
- [x] `encoding-down`
  - [x] PR or commit: https://github.com/Level/encoding-down/commit/8a23848c0956879ad4f81d3a048b204131875d02
  - [x] Release: 6.3.0
- [x] `subleveldown` (already had it)
- [ ] `multileveldown`
  - [x] PR or commit: https://github.com/mafintosh/multileveldown/pull/15
  - [x] ~~Release: not ours~~
- [x] `level-js`
  - [x] PR or commit: https://github.com/Level/level-js/pull/179
  - [x] Release: 5.0.0
- [x] ~~`leveldown`~~ (not needed now)
- [x] ~~`memdown`~~ (not needed now)
- [x] ~~`rocksdb`~~ (not needed now)

#### Use `reachdown` utility

- [x] `subleveldown` (`reachdown` itself was adapted from code in `subleveldown`)
  - [x] PR or commit: https://github.com/Level/subleveldown/pull/75
  - [x] Release: 4.1.3
- [ ] `multileveldown`
  - [x] PR or commit: https://github.com/mafintosh/multileveldown/pull/15
  - [x] ~~Release: not ours~~
- [x] `level-bench`
  - [x] PR or commit: https://github.com/Level/bench/commit/9f475d91eb4c50bbda5255aa60901ea44111bb66
  - [x] Release: 0.1.0
- [ ] `level-test` (in its tests)
  - [x] PR or commit: https://github.com/Level/level-test/commit/835040255d00aa6a91066757d749fdf462ca0201
  - [ ] Release: pending

**Comment by ralphtheninja** [comment]
Awesome name `reachdown` :)

**Comment by vweevers** [comment]
Closing because the remaining items are external (`multileveldown`) or tests-only (`level-test`).
